server:
  port: 8080


spring:
  application:
    name: demo20
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blue?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.wasu.demo20.bean
  mapper-locations: classpath:mapper/*.xml


#mappers 多个接口时逗号隔开
mapper:
  mappers: com.wasu.demo20.config.MyMapper
  not-empty: false
  identity: mysql

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql