spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/onthroad/spring-cloud-config
          username: 17719446375
          password: syl2091...
          search-paths: '{application}'
  security:
    user:
      name: syl
      password: 123456

server:
  port: 12580

