server:
  port: 9002


spring:
  application:
    name: server-consumer

  cloud:
    consul:
      host: 192.168.174.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}

