spring:
  application:
    name: Server-Provider #服务端
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://syl:123456@localhost:8080/eureka/
  server:
    enable-self-preservation: fasle