spring:
  application:
    name: feign-consumer


server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://syl:123456@peer1:8080/eureka/,http://syl:123456@peer2:8081/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true
