spring:
  application:
    name: demo51
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch?serverTimezone=UTC
    username: root
    password: root
