spring:
  application:
    name: Server-Provider

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://syl:123456@peer1:8080/eureka/,http://syl:123456@peer2:8080/eureka/
  server:
    enable-self-preservation: fasle
