spring:
  application:
    name: Server-Provider

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:123456@peer2:8081/eureka/http://syl:123456@localhost:peer1/eureka/
  server:
    enable-self-preservation: fasle
