spring:
  application:
    name: demo53
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch?serverTimezone=UTC
    username: root
    password: root