server:
  port: 8081

spring:
  application:
    name: Eureka-Server
  security:
    user:
      name: syl
      password: 123456

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://syl:123456@peer1:8080/eureka/

