server:
  port: 8080


spring:
  application:
    name: demo9
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml


  thymeleaf:
    cache: false
