spring:
  application:
    name: eureka-consumer

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://syl:123456@localhost:8080/eureka/,http://syl:123456@localhost:8081/eureka/