spring:
  application:
    name: eureka-consumer

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://syl:123456@peer2:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"