spring:
  application:
    name: eureka-consumer

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://syl:123456@peer1:8080/eureka/
    fetch-registry: true
    register-with-eureka: true