server:
  port: 8080
spring:
  application:
    name: demo10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml

logging:
  level:
    com:
      wasu:
        demo10:
          dao: debug