server:
  port: 8080
dubbo:
  application:
    # 服务名称，保持唯一
    name: server-provider
  registry:
    # zookeeper地址，用于向其注册服务
    address: zookeeper://192.168.174.133:2181  # 集群配置 zookeeper://127.0.0.1:2181?backup=127.0.0.1:2180,127.0.0.1:2182
  protocol:
    # dubbo协议
    name: dubbo
    # 暴露服务端口 （默认是20880，不同的服务提供者端口不能重复）
    port: 20880
