server:
  port: 8081

spring:
  application:
    name: Eureka-Server
  security:
    user:
      password: 123456
      name: syl
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://syl:123456@peer1:8080/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
